version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: soc_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: soc_user
      POSTGRES_PASSWORD: project_demo
      POSTGRES_DB: soc_platform
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
